Readme.md
lib/cheerio.js
lib/static.js
test/cheerio.js

I wanted to shore up the project's recommendation for extending Cheerio and back it with documentation and tests. This will allow us to be more confident in recommending this pattern in the future. Related issues: gh-621 & gh-589
Commit message:
> Ensure that each Cheerio function created with the `load` static method
> has a dedicated object in its prototype chain. This allows for
> conflict-free extension of the generated prototype.
>
> Additionally, expose the `fn` prototype alias as defined by jQuery and
> used by many jQuery plugins.

Isolate prototypes of functions created via `load`

---

.travis.yml

I think allowing failures here is the correct policy in principle, but we now have a practical reason to do so. From https://github.com/tmpvar/jsdom/issues/984 (Dec 20, 2014):
> I am not interested in taking on the support burden of working with unstable Node versions. Wait for iojs.
Commit message:
> Node.js version 0.11 is an unstable platform, meaning it may introduce
> breaking changes at any time. It is useful for the project maintainers
> to be aware of such failures (because they represent potential problems
> with the next stable release of Node.js), they should not block ongoing
> work.

Allow failures in Node.js v0.11

---

lib/api/traversing.js
lib/static.js
package.json

The new version supports `:matches` and includes a number of other improvements. I had to change the name due to a npm bug (upper case package names aren't supported anymore).
Fixes #644.

Update to css-select@1.0.0

---

Readme.md

Updates the Readme.md example given for the .not(function (index, elem))
function to correctly call .not(function (index, elem)).
Fixes #650.

Updates Readme.md: .not(function (index, elem))

---

package.json

I know I made a PR for this a few days ago (#653). But I think `~3.1.0` is too strict considering what cheerio is using from lodash (core methods): `_.each`, `_.forEach`, `_.map`, `_.defaults` and `_.merge`; these methods are not planned to change in the `3.x.x`  or anytime soon.
Being less strict is better for people using it with something like browserify (reduce bundle size by avoiding having 2 versions of lodash).
For example, from `3.1.0` to `3.2.0`, jdalton fixed some "important" issues in non-core methods (chaining): https://github.com/lodash/lodash/issues/955 and https://github.com/lodash/lodash/issues/958.
Another, maybe better and even less strict, solution can be: `3.x.x || 2.4.x`
Let me know what you think.

Change lodash dependencies to ^3.2.0

---

lib/static.js
test/api/utils.js

I'll admit that this is a bit esoteric, but as noted in the commit message (below), it *is* an inconsistency with jQuery.
For additional context: the current behavior is preventing [the Backbone.Layoutmanager project](https://github.com/tbranyen/backbone.layoutmanager) from upgrading its dependency on Cheerio because [it passes the result of `$.parseHTML` to `$.fn.replaceWith`](https://github.com/tbranyen/backbone.layoutmanager/blob/a7b012f314de96b988c2217ebee2a9330c1d6953/backbone.layoutmanager.js#L105-L115). I'm a maintainer of that project, so I'm a bit biased for this solution. I'd appreciate input on whether this change is an improvement for Cheerio or whether LayoutManager ought to be changed instead.
> Whenever Cheerio inserts a node as a child of a some other node, it
> explicitly …

Do not expose internal `children` array

---

Readme.md

Looking at [the code](https://github.com/cheeriojs/cheerio/blob/d41d8954f747c074e621d884e346f2f420df59de/lib/api/traversing.js#L143) or [tests](https://github.com/cheeriojs/cheerio/blob/d41d8954f747c074e621d884e346f2f420df59de/test/api/traversing.js#L212), I can see that these are there and tested, so why not advertise them! :-)
It also matches [the jQuery docs](http://api.jquery.com/nextAll/) now.
Thanks!

Add missing optional selector doc for {prev,next}{All,Until}

---

package.json

Hey Cheerio,
I updated css-select to the most up to date 1.1.0 because prior versions of css-select used prior versions of css-what which uses not fully supported `trimLeft`. (see https://github.com/fb55/css-what/pull/10).
Thanks!

update css-select dependency to ~1.1.0

---

lib/api/attributes.js
test/api/attributes.js

According to the description of `$.fn.data` (below), the method should
set the data for *all* elements in the selection. Ensure this does not
generate an error in those cases where any elements in the selection do
not yet define a `data` property.
> Store arbitrary data associated with the matched elements or return
> the value at the named data store for the first element in the set of
> matched elements.
Source: https://api.jquery.com/data/
This resolves gh-733

Enable setting data on all elements in selection

---

index.html

The links for the htmlparser2 options are broken. This commit has the correct links.
Also, it makes clear the names of the modules. there is aN "htmlparser" module, but cheerio uses "htmlparser2" (this can be confusing the newcomers).

update the links to DOMHandler and Parser-options documentation and clarify the names of the modules

---

Readme.md

Changed a part of line 117 of the Readme.MD from "an string expression" to "a string expression".
close #775

Fixed grammatical error

---

Readme.md
lib/cheerio.js

jQuery defines the `$.fn.toArray` method, and it is *not* deprecated, so
Cheerio should document and maintain it for the foreseeable future.

Reinstate `$.fn.toArray`

---

lib/api/traversing.js
test/api/traversing.js

I followed [the solution of fb55](https://github.com/cheeriojs/cheerio/issues/780#issuecomment-166870067) and I added a unit test to ensure that #742 and #780 was correctly fixed.

Fix unexpected behavior while querying child

---

Readme.md
lib/api/manipulation.js
test/api/manipulation.js

Some improvements was asked by @jugglinmike for the pull request #726 started by @digihaven,  which was intended to fix issue #641 by adding the two functions `.appendTo()` and `.prependTo()`.
This PR is a continuation of #726 and try to fix it.
---
- Fix incorrect indentation
- Fix the two test description provided
- Extend arguments for `.appendTo()` and `.prependTo()`
- Based on jQuery documentation, these two functions accept also Node and Array as argument.
- As `a.appendTo(b)` is actually just `b.append(a)`, the function has to convert the target to a Cheerio object as long as it is not one already.
- Add unit tests to `.appendTo()` and `.prependTo()`
- These test case are intended to verify the correct behavior of functions for different arguments accepted according to the jQuery …

Fix PR #726 adding `appendTo()` and `prependTo()`

---

lib/api/manipulation.js
test/cheerio.js

Fix for passing non-string values to .html or .text

---

lib/api/attributes.js
test/api/attributes.js
test/fixtures.js

As noted in #633, we are not properly treating `option's` without a `value` attribute. This PR adds back functionality that emulates the DOM and thus jQuery behavior. In this PR:
- Added tests for value-less options (e.g. normal, with HTML entities, with HTML elements)
- Correct expectations can be found at http://codepen.io/twolfson/pen/WbymMK
- Added patches for `attr` and `val`

Added support for options without a `value` attribute. Fixes #633

---

lib/api/attributes.js
test/api/attributes.js
test/fixtures.js

While working on #632 to find some edge cases jQuery is covering, I found a regression with checkboxes and radio inputs. In the browser, it will default to `on` as the value when no value attribute has been specified.
http://codepen.io/twolfson/pen/bNKJBZ
This PR fixes that by patching in on `.val()`. In this PR:
- Added regression test for valueless radios and checkboxes
- Added fix for valueless radios and checkboxes

Added default value for checkboxes/radios

---

lib/api/forms.js
test/api/forms.js
test/fixtures.js

This was originally opened as #632 but @twolfson lost write access to the source repo and there was a merge conflict so we resolved it all in this PR
-------------------------
Now that #631 is implemented, we can add `.serialize()` support. Unfortunately, this comes with adding `$.param()`. `$.param` has a second half that `.serialize()` doesn't leverage (see its `else` statement). I am not sure whether we want to add this/test it, or drop it and make `$.param` internal only for now.
In this PR:
- Added `.serialize()` support http://api.jquery.com/serialize/
- Added tests for `.serialize()`

Added `.serialize()` support. Fixes #69

---

lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/static.js
package.json
test/cheerio.js
test/xml.js

May help with #862.
I replaced lodash with individual packages for each function. This brought down the size by ~4mb. Not too bad!

Use individual lodash functions

---

lib/api/attributes.js
test/api/attributes.js

Fix for issue https://github.com/cheeriojs/cheerio/issues/875.

.prop now returns undefined if given an invalid element or tag (#875)

---

lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/static.js
package.json
test/cheerio.js
test/xml.js

As of lodash 4.14.0, individual packages (e.g. `lodash.foreach`) are zero-dependency modules (see the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v4140)), meaning that if you install several of them, they do not share any code.
This completely negates (and actually worsens) the bundle size savings introduced in #864, since cheerio now depends on so many individual method packages. The solution is to use the modular version of lodash (installing lodash and importing from `lodash/method` rather than from the `lodash` monolith) as mentioned [here](https://github.com/cheeriojs/cheerio/pull/864#issuecomment-234014347).

Use modular lodash package

---

.jshintrc
lib/api/attributes.js
lib/api/forms.js
lib/api/manipulation.js
test/api/attributes.js
test/api/manipulation.js
test/api/traversing.js
test/cheerio.js

@ssp raised this concern during the review of gh-718. I'm inclined to agree that shadowing is a hazardous practice that ought to be avoided, but I don't know where the rest of @cheeriojs/owners stand. Do you folks care to weigh in on this?
Commit message:
> When variable binding identifies are re-used in nested scopes
> ("shadowing"), code readability suffers. The same identifier may
> describe many distinct values in memory, and the process of
> disambiguating requires explicit attention from the reader. Mistakes
> made in this process can trigger bugs which, unlike unresolvable
> references, are not immediately apparent.
> 
> Configure JSHint to warn on occurrences of nested reuse of variable
> binding identifiers in order to promote code clarity. Update the
> codebase to satisfy this …

Disallow variable shadowing

---

Makefile

Due to occasional unavailability in the code coverage reporting service,
the continuous integration environment does not reject builds that
experience issues with this task.
This behavior was previously implemented in such a way to allow errors
of *any* kind--including test failures. Re-implement to limit the scope
of "allowed errors," to the reporting command only.

Report test failures in CI

---

Readme.md

- Previously docs contained examples using a mix of ES5 and ES6 syntax as well as some missing variable declarations.
- The first example (that did use ES6) used let instead of const, it seems to be considered best practice to use const when ever possible (i.e. when a pointer is not going to change, even if it's value does in the case of objects an arrays)

Standardise readme on ES6 variable declarations (closes #1001)

---

lib/static.js
test/api/utils.js

[ First time pull :) ]
text function will ignore script and style tags
Should solve this problem: https://github.com/cheeriojs/cheerio/issues/986

.text() ignores script and style tags

---

Readme.md

The project frequently receives bug reports from new users who expect
full web browser behavior. The project documentation does not make it
particularly clear that such functionality is out-of-scope for the
project. It includes some text that is specific to the JSDom project,
but that explanation assumes familiarity with JSDom, and its location
at the end of the file makes it easy to miss.
Explicitly describe the scope of the project in the introductory section
of the README file, prior to API documentation and remove the
JSDom-specific text.

Clarify project scope in README file

---

Readme.md

I noticed that the `serialize` method was not documented. I didn't see anything in the code indicating that it was deprecated and only exists for backwards compatibility.

Add Missing serialize Documentation

---

History.md

Incorporate recent feedback from consumers who have experimented with
the version 1.0 release candidate.
---
@fb55 @ljharb: I've re-written the guide based on Jordan's experience migrating
the Enzyme project to the release candidate. Think this is an improvement? Is
there anything else you'd like to see here?
While writing this, I began to question the importance of Cheerio's `<root>`
element. I'm proposing a more drastic change for version 1.0 over at gh-1077.
I'd love to hear your thoughts on that, too!

Re-write migration guide for version 1.0

---

lib/api/attributes.js
test/cheerio.js

fixes #944
Added an ‘outerHTML’ case to the switch in the prop function, which wraps a clone of `this` in a container element, and sets `property` to that container's HTML

#944 fixing missing prop(‘outerHTML’) implementation.

---

Makefile

This includes code coverage reports as generated by the command `make
test-cov`.

Do not lint files excluded from version control

---

lib/api/manipulation.js
test/api/manipulation.js

Rebased version of #588. We can still optimise performance later on, this works for now.

Ensure text nodes expose the DOM level 1 API

---

package.json

DoS/RCE vulnerability in lodash@4.15.0
After change, scanning the repo via Snyk did not reflect any issues. Test suite ran showing 598 passing tests with 1 test pending.

Fix for issue #1175 - Update lodash for DoS/RCE vulnerability in lodash@4.15.0

---

lib/api/attributes.js
lib/api/manipulation.js
test/api/utils.js
test/cheerio.js
test/xml.js

Promote consistency in variable names within the project's source and
unit tests. This helps to highlight the distinction between the object
exported by the module and the function produced by the `load` method.
The latter value is expected to mimic the jQuery API, while the former
value generally should only be used for a small set of methods specific
to Cheerio:
- `load`
- `html`
- `xml`
- `text`
Other usages of the exported object are discouraged, and a future patch
will update the unit tests to reflect the usages that are endorsed for
long-term stability.
---
Hey @fb55.
My plan to accomodate gh-1122 in version 1.0 is to document the irregular API as "deprecated" but also to improve test coverage. Currently, our coverage is incomplete, and that's particularly hard to see given the …

Improve variable names

---

test/api/utils.js
test/cheerio.js

Okay, @fb55; here's the next step for gh-1122 :)
---
Methods named `load`, `html`, `xml`, and `text` are defined in many
locations:
Today, Cheerio defines multiple versions of methods named `load`,
`html`, `xml`, `text`, and `parseHTML`. These alternate versions may be
defined in up to three distinct parts of the API:
- exported by the Cheerio module
- as static methods of the "loaded" Cheerio factory function
- as instance methods of the "loaded" Cheerio factory function
Some of these are surperfluous, and because some unecessarily conflict
with idiomatic jQuery coding patterns, they have been designated for
future removal [1].
Add tests for the deprecated methods in order to avoid regressions prior
to their removal. Insert comments to delineate the methods which are
endorsed and which …

Formally test deprecated APIs

---

package.json

Moves lint and test script call from Makefile to package.json. Makes the test run on all platforms.

Fix running test on Windows

---

package.json

Tests run successfully.  This is specifically to fix projects including cheerio failing to compile as ES3 TypeScript (see #1245), which [seems to be what 3.0.1->4.0.0 addresses](https://github.com/inikulin/parse5/blob/master/docs/version-history.md#400).

Updated parse5 to 4.0.0 (fixes #1245).

---

package.json
test/cheerio.js

Version 0.1.1 of the dom-serializer module has corrected the way boolean
attributes are rendered when interpreted as HTML. Update this project's
expectations accordingly and explicitly rely on the release which
includes the fix.
---
@fb55 our "1.0.0-rc2" release is far behind what we're currently preparing for 1.0.0, but since the state of the tests are relevant for Node's tooling, I wanted to hot-fix this immediately. I created the base branch so we could release just the correction to the test (it's not an issue on the in-progress "v1.0.0" branch). If it looks right to you, could you merge and publish a new release candidate?

Update test expectation

---

test/api/utils.js

Refs: https://github.com/nodejs/citgm/issues/605
Refs: https://nodejs.org/api/deprecations.html#deprecations_dep0005_buffer_constructor

Do not use the deprecated Buffer() constructor

---

lib/parse.js
test/parse.js

Hello! :raised_hands: 
This PR attempts to bring back options passing to parse5.
Addresses(and closes) #1296 
- Introduces a way to pass options to parse5 if cheerio ends up using it
- Adds a test for checking whether it's possible to get the location info
I didn't know which base to use for this PR, so I made it on top of `v1.0.0-rc.3`
Please let me know if anything needs to be changed!

Pass options to parse5 to enable location info

---

lib/static.js
test/api/utils.js

This change normalizes rendering between trees generated by parse5 and
htmlparser2. Consistent rendering of the "root" node is especially
important given that `cheerio.render($.root())` will be the recommended
pattern for rendering entire documents in Cheerio version 1.0.

Correct rendering of root node

---

package-lock.json
package.json

What about this being v1.0.0-rc.4 ?
Test result (same as before lodash version bump):
```
650 passing (1s)
1 pending
```

Fixing lodash vulnerability

---

.eslintrc.json
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/options.js
lib/static.js
test/cheerio.js
test/parse.js
test/xml.js

Lodash is quite big package https://packagephobia.com/result?p=lodash
and often used where modern javascript feature do a good job.
In this diff I replaced lodash with native functions or for/of loop.
The only left case is lodash/cloneDeepWith which does not have clear
alternative. I will try to replace it with something in another PR and
remove lodash dependency.

Avoid lodash where possible

---

Makefile
package-lock.json
package.json
tsconfig.json
types/index.d.ts
types/index.test-d.ts

This is an attempt to pull in the Cheerio types from DefintelyTyped so that they're available to all JS users, and so TS + JS users are assured that the type definitions match the version of the library they are using without having to determine the correct version of the @types/cheerio package.
It's the first time I've done this, so feedback from knowledgeable people would be very welcome.
I have two specific questions:
1. I've added `@types/node` to dependencies because the types use `Buffer`. Does the library target the browser and React Native? If so will including `@types/node` as a dependency cause problems? Is it preferable to use [a reference](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)?
2. In DT, the type defs close with `declare module 'cheerio'`. …

Pull in types from DefinitelyTyped

---

types/index.d.ts

Improves the accuracy of types, by using the types that `domhandler` already provides.

refactor(types): Use `domhandler` DOM types

---

Readme.md
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/options.js
lib/parse.js
lib/utils.js
package-lock.json
package.json
test/api/manipulation.js
test/api/utils.js
test/parse.js

BREAKING: This removes the `root` property from top-level nodes. Instead, the `root` reference is kept in the (previously `null`) `parent` property. Cheerio now uses the root object generated by either of the parsers.
Also bumps `css-select`, as the new version includes a fix for `parent` references that aren't elements.

refactor: Use the parser's DOM without modifications

---

lib/api/manipulation.js
lib/parse.js
lib/utils.js
package-lock.json
package.json

Avoids unnecessary parser calls. Fixes #1166.
Allows us to drop lodash. Fixes #1506.

refactor: Use `domhandler` nodes directly

---

.eslintrc.json
lib/api/traversing.js
lib/static.js
package-lock.json
package.json
test/api/attributes.js
test/cheerio.js

Adds support for jQuery positional selectors (:eq, :first, :not(:last) etc.).
Fixes #1355
Fixes #129

feat: Use `cheerio-select`, to support positional selectors

---

lib/static.js
test/xml.js

We passed the wrong option to `render` (should have been `xmlMode`, was `xml`).

fix(xml): Fix `.xml` calls on HTML documents

---

lib/options.js
lib/static.js
test/cheerio.js
types/index.d.ts
types/index.test-d.ts

Passing `xml: { xmlMode: false }` is now going to use `htmlparser2`.
The types now use htmlparser2 option types and include the `xml`, `sourceCodeLocationInfo` properties.

fix(options): Handle `xml: {xmlMode: false}`, simplify types

---

lib/api/manipulation.js
lib/parse.js
lib/utils.js

`isTag` now no longer returns `true` when passed a string, which seems like it was unintended in the first place. (There are several locations in the codebase that would break should an element be just a string instead of a Node object.)

refactor: Use domutils for `isTag`, removing elements

---

lib/api/attributes.js
test/api/attributes.js

Fixes #554
This makes cheerio behave like jQuery with these values.
Tests were part of the issue above, contributed by @iwarren.

fix(attr): Fix handling of `undefined` as value

---

types/index.d.ts

to allow setting isDocument to false (and passing null to options)

Update TypeScript bindings

---

.eslintrc.json
benchmark/suite.js
lib/api/attributes.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/parse.js
lib/static.js
test/api/deprecated.js
test/api/manipulation.js
test/api/utils.js
test/cheerio.js
test/xml.js
types/index.d.ts

Introduces a lot of changes that are necessary for future-proofing the project. Also includes some general code improvements in sections that already needed a few changes.

refactor: Declare vars when used, streamline code

---

lib/parse.js
lib/parsers/htmlparser2.js
lib/parsers/parse5.js
lib/static.js

First step to allow us to provide different entry points for different needs.

refactor: Move parsers to their own files

---

.eslintrc.json
index.js
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/options.js
lib/parse.js
lib/static.js
lib/utils.js
package-lock.json
package.json
test/api/deprecated.js
test/api/traversing.js
types/index.test-d.ts

Adds JSDoc comments for a couple of methods, `@returns` everywhere it was missing and introduces some additional lints. Also introduces a Prettier plugin to automatically format all JSDoc comments.

docs(jsdoc): Add docs, standardize

---

CONTRIBUTING.md
Readme.md
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
test/api/attributes.js
test/api/traversing.js
types/index.d.ts

There are only a few http links left in tests but those shouldn't matter a lot.
Should fix the mixed content issues on https://cheerio.js.org/

Use https when possible.

---

package.json

This was failing on Windows native cmd. Using double quotes should work everywhere.

package.json: fix `format:prettier:raw` script

---

.github/dependabot.yml

I went with a weekly schedule on Wednesday, but feel free to let me know or edit the PR to adapt it to your needs.
BTW, have you thought about using `versioning-strategy: increase` for the npm check?

dependabot: update GitHub Actions too

---

.gitignore
.prettierignore
Makefile
lib/api/manipulation.js
package-lock.json
package.json
test/.eslintrc.json
test/__fixtures__/fixtures.js
test/api/attributes.js
test/api/css.js
test/api/deprecated.js
test/api/forms.js
test/api/manipulation.js
test/api/traversing.js
test/api/utils.js
test/cheerio.js
test/parse.js
test/xml.js

Jest has the same minimum Node version as Mocha, but comes with a lot of batteries included (eg. coverage, assertions), which helps with making things more predictable.
Most of these changes were made using `jest-codemods`.

test: Migrate to Jest

---

package.json

This seems redundant as a direct dependency AFAICT.

Remove the unused direct entities package

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/lint.yml
.github/workflows/site.yml
.travis.yml
Makefile
Readme.md
package-lock.json
package.json

It seems there are a few issues:
1. ~~.travis.yml was using `make travis-test` but that was using `@npm run test:lint` which doesn't exist; I changed it to `@npm run lint` but the makefile isn't up to date.~~ **EDIT**: I switched to `npm test` but IMHO the Makefile should be removed to avoid confusion since it's clearly broken
2. it seems `make travis-test` is failing; `test-cov` also doesn't seem to work. Happy to sort everything out as long as you give me some hints. My suggestion is to move everything to npm scripts only and Actions including coverage.
3. I added another job with `BENCHMARK=true` 
4. We can add further Node.js versions, OS etc. Let me know and I can take a stab at it later. I'd just split lint to a separate action or job and run it only once.
Notes:
1. since Actions …

Switch to GitHub Actions CI

---

jsdoc-config.json

**Untested yet**
I need to check if there are any duplicate IDs and how the plugin handles that case.

JSDocs: enable Markdown IDs

---

.eslintrc.json
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/parse.js
lib/static.js
lib/utils.js
types/index.d.ts
types/index.test-d.ts

And rename unused vars to `_` and remove unused `cloneDom` argument.
Found by enabling the TypeScript compiler for the repo. This unfortunately still leads to many many false positives, which have to be resolved independently.

fix(jsdoc): Fix parameter types

---

Readme.md

Apparently jsdoc's Markdown wrongfully escapes `//` in angle bracket links

Readme.md: fix link

---

lib/api/manipulation.js
lib/parsers/parse5.js
test/api/manipulation.js

using proper context when parsing in .html() 
It solves #1083

.html() send context to parse5

---

test/api/attributes.js
test/api/manipulation.js
test/api/traversing.js

Also, remove some trailing spaces from descriptions.
Might be worth adding https://github.com/jest-community/eslint-plugin-jest later :)

Prefer Jest's toBe true/false matcher.

---

.eslintrc.json
lib/api/attributes.js
lib/api/css.js

This should match what's currently used AFAICT. I left `null` out because it's handy to keep it.

ESLint: enable eqeqeq rule expect for null

---

lib/api/manipulation.js
lib/api/traversing.js
test/__fixtures__/fixtures.js
test/api/manipulation.js
test/api/traversing.js
test/cheerio.js
test/parse.js

added/changed some tests so more conditions would be covered

added some tests

---

lib/api/traversing.js
test/api/traversing.js

parent() don't work well in functions if selector is undefined
``` javascript
function getParent(el, parent) {
return el.parent(parent).not('body');
}
var parent = getParent($('#rating span'))
```
In [.parent()](https://github.com/cheeriojs/cheerio/blob/703ec166d8b98aab714ad8930858bbefaed847b1/lib/api/traversing.js#L89) has condition:
``` javascript
...
if (arguments.length) {
...
```
but it will fail if used like in function above, since `arguments.length` will be 1 even when `selector` is actually undefined.

parent() may fail in functions

---

lib/api/manipulation.js
test/api/manipulation.js

Added unwrap function

---

test/api/attributes.js
test/api/css.js
test/api/manipulation.js
test/api/traversing.js
test/cheerio.js

There's one case where tests fail; I added a comment there, but I'm not sure if it's a bug or not.
EDIT: I think it's intended but please confirm so that I revert that part.

tests: prefer using `.toBeUndefined()`

---

types/index.d.ts
types/index.test-d.ts

code snippet
https://github.com/cheeriojs/cheerio/blob/main/lib/api/attributes.js#L113
```js
value.call(el, i, el.attribs[name])
```
the first argument is thisArg not the function args

fix(typing): AttrFunction

---

lib/api/manipulation.js

fix **jsdoc** so **wrap** & **wrapInner** would be shown as methods

fix jsdoc so wrap & wrapInner would be shown as methods

---

lib/api/traversing.js
test/api/traversing.js

It seems **lodash** filter returns new empty array even when collection is undefined.
Should fix #1679

Filter text nodes in find function

---

index.js
lib/load.js
lib/static.js

- move **.load()** function own file so api methods could access other static functions early.
- load **load.js** file after cheerio object is built.
should solve #1311 & #1689
it passes rollup test

remove node module caching dependency

---

lib/cheerio.js
lib/static.js
test/api/deprecated.js

* Add length parameter for all cheerio instances.
* re do merge with simple postfix operators
should resolve #1674

add length property for all cheerio instances

---

types/index.d.ts

fixes #1540, fixes #1649 
**Note:** I don't know what I'm doing, but this fix *seems* to be working for my case
In these examples, the code compiles and the console.log output `Hello` as expected
```ts
import cheerio from 'cheerio';
const $: cheerio.Root = cheerio.load('<div>Hello</div>');
console.log($('div').text());
```
```ts
import cheerio, { Root } from 'cheerio';
const $: Root = cheerio.load('<div>Hello</div>');
console.log($('div').text());
```
```ts
import type { Root } from 'cheerio';
import cheerio from 'cheerio';
const $: Root = cheerio.load('<div>Hello</div>');
console.log($('div').text());
```
Tested with this tsconfig: https://gist.github.com/dominik-korsa/5888e24c196e50fa673154e030cf11ce
I wasn't able to test CommonJS (`require()`) syntax

Export all interfaces in declaration file

---

types/index.d.ts

Reflects missing ts declaration of this line:
https://github.com/cheeriojs/cheerio/blob/897b37fb671382e8f804d8f1f15e379964f48ad2/lib/cheerio.js#L139

Allow foreach loops in typescript

---

test/api/traversing.js

The added `return` is to prevent linter errors due to the rule `array-callback-return` (which is probably why the `.map` call was originally replaced with `.each`).
Closes #1705.

Fix wrong method used in `.map` tests

---

lib/utils.js
test/cheerio.js

Now allows a `#` before the string.
BREAKING: Now requires a letter directly after the `<`. Both parsers would have parsed this as text before.
@5saviahv #1699 was a great find, thanks for opening it! I wasn't sure about the actual implementation, here is my take; with it, we still allow text around the actual string, but ban things that definitely aren't tags (see breaking).

refactor(utils): Simplify `quickExpr`

---

lib/parsers/parse5.js
test/__fixtures__/fixtures.js
test/cheerio.js
types/index.d.ts
types/index.test-d.ts

Expose [scriptingEnabled](https://github.com/inikulin/parse5/blob/master/packages/parse5/docs/options/parser-options.md#optional-scriptingenabled) option. It would accept `false` value only, all other cases it should stay true.
``` html
<noscript><link rel="stylesheet" href="/css/noscript.css"></noscript>
```
It should help parse some documents where `noscript` elements are used. 
If **true** (_default_) all html code inside `noscript` elements will treated as text,
if **false** all html code inside `noscript` elements will treated as html and parsed accordingly.
#1105

expose parse5 option scriptingEnabled

---

lib/api/traversing.js
test/api/traversing.js

- parentsUntil selector accepts multiple results.
- parentsUntil filter didnt filter

small parentsUntil fixes

---

lib/api/traversing.js
test/api/traversing.js

Continuation of #1708, fixing up `untilNodes` for `{prev,next}Until`.

fix(traversing): Fix filter for `{prev,next}Until`

---

package-lock.json
package.json
test/api/traversing.js

Same as #1729 except I updated failed test
apparently order of objects should be correct this time.

cheerio-select 1.1.0 -> 1.2.0

---

test/api/traversing.js

`.add` function had some 3rd and 4th level nested tests.
- looking from output those indentations are rather subtle and no longer easily readable, I moved them to 2nd level and added argument descriptions used in tests.
- Also those deeply nested tests aren't very easy to follow in code.
- no actual change in tests, just formatting.

nesting level of some deeply nested tests decreased

---

lib/api/manipulation.js
lib/api/traversing.js

according to documentation functions [after](https://cheerio.js.org/Cheerio.html#after), [before](https://cheerio.js.org/Cheerio.html#before), [slice](https://cheerio.js.org/Cheerio.html#slice) doesnt have arguments, added argument definitions.

add after, before, slice arguments into jsdoc.

---

lib/api/manipulation.js
test/api/attributes.js

- updated some tests, so they will try functions with mixed text and html tags
- updated addclass function test so it will try elements without already existing class name

mix text and html tags in tests

---

lib/api/attributes.js
test/api/attributes.js

function .attr() - handle value undefined like jQuery does it.
should fix #1664

function .attr() - handle value undefined like jQuery 

---

Readme.md
src/__tests__/deprecated.spec.ts
src/api/forms.spec.ts
src/api/forms.ts
src/api/manipulation.spec.ts
src/api/manipulation.ts
src/api/traversing.spec.ts
src/api/traversing.ts
src/cheerio.spec.ts
src/cheerio.ts
src/index.ts
src/load.ts
src/static.spec.ts
src/static.ts

This removes quite a few currently necessary hacks.
__BREAKING CHANGES__
Low potential for breakages:
- Removed the internal `_originalRoot` property. Some methods, such as `appendTo`, can now have their roots overwritten by passing the `root` property to `CheerioAPI`.
- The `default` export now has a surrounding `Document`, without any contents.

refactor: Have `load` export a function

---

src/api/attributes.ts
src/api/traversing.spec.ts
src/api/traversing.ts
src/types.ts

fix(traversing): Make `filter` work on all collections

---

src/api/attributes.ts
src/api/css.ts
src/api/manipulation.ts
src/api/traversing.ts
src/cheerio.spec.ts
src/utils.ts

Removes a lot of `_` variables.

refactor: Change order of arguments of internal `domEach`

---

src/api/attributes.spec.ts
src/api/attributes.ts

fix(attributes): Boolean attributes should not be special in xmlMode

---

.eslintrc.json
Readme.md
src/cheerio.spec.ts

As proposed by @n1xx1 in https://github.com/cheeriojs/cheerio/issues/1778#issuecomment-855245868
Fixes #1778

chore(plugins): Document & use TS type definition

---

package-lock.json
package.json
src/api/traversing.ts
src/cheerio.ts

Querying can now be sped up in some cases by supplying the `root` of the document. Also, `filter` now accepts any node and no longer needs a `isTag` check.

refactor(traversing): Bump cheerio-select, adopt changes

---

package-lock.json
package.json
src/api/manipulation.ts
src/api/traversing.ts
src/parse.ts
src/static.ts
src/utils.ts

Simplifies some imports, and allows Cheerio to pull in updates.

refactor: Use `domutils` module directly

---

src/utils.ts

Should perform slightly better, and we are not at the whim of a regex engine for guaranteed linear performance.

refactor(utils): Hand-roll `isHTML`

---

src/api/manipulation.spec.ts
src/api/manipulation.ts

fix(manipulation): Have `text` turn passed values to strings

---

src/api/traversing.ts

Makes the docs match the implementation and is in line with jQuery.
Fixes #2056

refactor(traversing): Only return elements in `closest`

---

Readme.md

Might help the users to understand what the differences are between such projects (browser automation vs. emulated DOM).

docs(readme): update "is not a web browser" section

---

src/__fixtures__/fixtures.ts
src/api/attributes.spec.ts
src/api/attributes.ts

feat(attributes): Add `textContent` and `innerText` props

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/sponsors.yml

- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: neilnaveen <42328488+neilnaveen@users.noreply.github.com>

Set permissions for GitHub actions

---

.eslintrc.json
benchmark/benchmark.ts
benchmark/suite.ts
package.json
src/__tests__/deprecated.spec.ts
src/__tests__/xml.spec.ts
src/api/attributes.spec.ts
src/api/attributes.ts
src/api/css.spec.ts
src/api/css.ts
src/api/forms.spec.ts
src/api/forms.ts
src/api/manipulation.spec.ts
src/api/manipulation.ts
src/api/traversing.spec.ts
src/api/traversing.ts
src/cheerio.spec.ts
src/cheerio.ts
src/index.spec.ts
src/index.ts
src/load.ts
src/parse.spec.ts
src/parse.ts
src/parsers/parse5-adapter.ts
src/slim.ts
src/static.spec.ts
src/static.ts
src/types.ts
src/utils.ts

This makes Cheerio a dual ESM / CJS module.

feat: Add ESM

---

src/__tests__/deprecated.spec.ts
src/api/attributes.spec.ts
src/static.spec.ts
src/static.ts

Reverts #1018
Fixes #1050
To keep the current behaviour, you can use `.prop('innerText')` (added in #2214).

fix(text): Include script and style contents

---

src/api/attributes.spec.ts
src/api/attributes.ts
src/options.ts

If `baseURI` is defined, `.prop('src')` and `.prop('href')` will resolve URLs. Only works if the global `URL` object is available.
Fixes #1140

feat(attributes): Add `baseURI` option

---

src/api/traversing.ts
src/index.ts
src/options.ts

This allows users to provide their own custom `pseudos`. Other options will now also work as expected.
The old extension points for pseudos has been deprecated and will be removed in a future version.

feat: Pass options to `cheerio-select`

---

src/index.ts
src/slim.ts

We now export `AnyNode`, as well as `ParentNode`. `NodeWithChildren` is no longer exported — please use `ParentNode` instead.
Also makes static exports explicit.

refactor(exports): Update exported values

---

src/api/attributes.spec.ts
src/api/attributes.ts

fix(attributes): Align `prop` undefined handling with jQuery

---

package.json

As used by Enzyme here (and which broke after upgrading Cheerio):
https://github.com/enzymejs/enzyme/blob/master/packages/enzyme/src/Utils.js#L11
Fixes #2600

fix(package): Allow imports of `cheerio/lib/utils`

---

Readme.md

I removed a code example about a deleted option.
The `normalizeWhitespace` property was extended from [domhandler](https://github.com/fb55/domhandler), but that package deprecated the property at [21a2f7](https://github.com/fb55/domhandler/commit/21a2f7b6a53c0c61e4c753589c5ba99e611529c9), and removed it at [6503e2](https://github.com/fb55/domhandler/commit/6503e2d22bc1896cfb9553296f761856dc68a27f) finally.
I can't find a replacement, so I just removed the property in README.md.

docs: remove example for removed option

---

.github/workflows/site.yml

No need to go through a `gh-pages` branch.

chore(ci): Deploy to GitHub Actions directly

---

src/api/attributes.spec.ts
src/api/attributes.ts

Removed several unnecessary branches, and streamlined the code.

fix(attributes): Allow empty string in `data`, and simplify

---

benchmark/suite.ts
package-lock.json
package.json
src/node.spec.ts
src/node.ts
tsconfig.json

feat: Add functions to load buffers, streams & URLs in NodeJS

---

src/__tests__/deprecated.spec.ts
src/index.spec.ts
src/index.ts
src/load.ts

Fixes #2692
Also moves deprecation notes to the relevant definitions.

fix(index): Bind static `html`, `xml`, and `text`

---

src/api/manipulation.spec.ts
src/batteries.spec.ts
src/batteries.ts
src/cheerio.spec.ts
src/index.ts
src/load.ts
src/options.ts
src/parse.spec.ts
src/parsers/parse5-adapter.ts
src/static.ts

Fixes https://github.com/cheeriojs/cheerio/issues/2744. I'm not quite happy yet, but am out of ideas of how to improve the situation without breakages in JS code.
htmlparser2 options have been moved out of the root options for Cheerio, making it more obvious which options will take effect. This only affects the TypeScript type.
Users that want to use htmlparser2 should use the `xml` option:
```js
const $ = cheerio.load('<html>', { xml: {
withStartIndices: true
}})
```
Just as before, users are still able to force htmlparser2 using a combination of `xml` and `xmlMode`:
```js
const $ = cheerio.load('<html>', { xml: {
// Force `htmlparser2`, but parse document as HTML.
xmlMode: false
}})
```

refactor(options): Revamp option handling

---

src/__fixtures__/fixtures.ts
src/__tests__/deprecated.spec.ts
src/api/attributes.spec.ts
src/api/css.spec.ts
src/api/forms.spec.ts
src/api/manipulation.spec.ts
src/api/traversing.spec.ts
src/cheerio.spec.ts
src/static.spec.ts

For tests, this PR:
- Gets rid of many re-assigned variables,
- Replaces most `any` uses with `never` (which makes it clearer that we are testing an edge-case that shouldn't be allowed by TS)
- Simplifies imports to be from fewer files.

chore(test): Unify test structure, use `never`

---

src/api/manipulation.spec.ts
src/api/traversing.ts

And add a test for `empty` with comment nodes.

refactor(traversing): Simplify `_matcher`

---

package-lock.json
package.json
src/batteries.ts

`htmlparser2`'s `WritableStream` comes with a `TextDecoder` instance that is not needed for cheerio's use-case. It is easy enough to use a custom stream here to avoid potential complications.

refactor(batteries): Bump `htmlparser2`, use custom stream

---

package.json
tsconfig.json

👋 Hey, I work on the TypeScript team, and in 5.2 we’re planning to [break your tsconfig](https://github.com/microsoft/TypeScript/pull/54567), so I’m opening a PR to preemptively fix it. Specifically, we’re going to enforce that `module` and `moduleResolution` have to be set to the same value when either is `node16` or `nodenext`.
You’re currently using `moduleResolution: node16` in combination with both `module: commonjs` and `module: esnext` in order to achieve dual module format emit with tsc. tsc isn’t really designed to work with those combinations, as explained in the afore-linked PR. Those limitations are why you were susceptible to issues like #2759 and need the eslint rule that enforces file extensions on import paths. Really, TypeScript should be doing that validation for you. …

fix(types): Fix module/moduleResolution options for TypeScript 5.2

---

.github/workflows/site.yml

Hey! 🙂
I've made the following changes to your workflow: 
- Avoid running CI related actions when no source code has changed
- Running workflows which build or test certain parts of the code base without these parts being changed is useless, as nothing new will be checked or created.
- Steps should only perform a single command
- When one step does multiple things at once, it becomes unclear what exactly has failed during the execution of the step.
- Avoid deploying jobs on forks
- Deploying from a fork is usually not wanted because in that case unreviewed code by external authors will be published/deployed to main. Furthermore, forks usually don't have the correct rights to publish/deploy and will fail the workflow anyway.
I've fixed these smells in (part of) your workflows, and I'm …

Fix potential github action smells

---

src/index.ts
src/options.ts
src/slim.ts
website/docusaurus.config.js

This made the docs difficult to read, as all types ended up in the docs.
BREAKING CHANGE; if you previously imported node types from Cheerio, you will now have to import them directly from `domhandler`.

refactor: Remove type re-exports

---

src/api/traversing.spec.ts

chore(traversing): Add test case for `lowerCaseTags`

---

src/index.ts

The example [in the docs](https://cheerio.js.org/docs/api/functions/loadBuffer) uses `cheerio.fromBuffer` instead of `cheerio.loadBuffer`, which confused me for a second when copy-pasting.

docs: correct loadBuffer() name in example

---

package.json

Fixes https://github.com/cheeriojs/cheerio/issues/4032
Some bundlers (e.g. react-native) requires the field `browser` at `package.json` root to find the correct resolution entry points. (Reference: https://metrobundler.dev/docs/configuration/#resolvermainfields)
This PR adds the correct entry point for browsers to `package.json`.

Add a field `browser` to `package.json` root

---

src/api/extract.spec.ts
src/api/extract.ts

Noticed this while working with `extract`
TypeScript does not automatically distribute conditionals unless the generic type itself represents a union. So, in `ExtractedValue`, `V['value']` is not distributed unless inferred as a separate generic type.
EDIT: Adding [issue link](https://github.com/cheeriojs/cheerio/issues/4335#issue-2769048688)
```
// Testing distributed conditional over an indexed access type
interface Obj {
value: string | number;
}
type TestIndexedObj<V extends { value: unknown }> = V['value'] extends number ? 'extends number' : 'does not extend number';
type TestIndexedObjResult = TestIndexedObj<Obj> // "does not extend number"
// Testing distributed conditional over a union
type ObjValue = Obj['value'];
type TestUnion<V> = V extends number ? 'extends number' : 'does …
```

fix(types): fix ExtractedValue type
