cheeriojs/cheerio

index.html

As mentioned in #657, not sure if this site is being maintained anymore.  But this example matches the example on the readme and works as intended.

add get method to .map example

---

package.json

Update to dom-serializer@0.1.0

---

lib/api/attributes.js
test/api/attributes.js

The fix was part of #642, I've added a test case.

Handle malformed JSON in data attributes

---

Readme.md

.data('data-apple-color')
->
.data('apple-color')

fix document's mistake in Readme.md

---

Readme.md
lib/api/manipulation.js
lib/cheerio.js
lib/utils.js
test/api/manipulation.js

@dandlezzz started on this implementation in gh-558. I offered to finish up for him, got distracted by a more fundamental patch that it necessitated (see gh-574), then forgot about it. I've just now brought it back up to speed.
I've squashed Daniel's original work into  single commit and applied my own changes on top in order to clearly document this collaboration.
Supersedes gh-558
Resolves gh-541

Implement `$.fn.wrap`

---

.npmignore
package.json

Fix npm files filter

---

package.json

@Delgan fixed a long-standing bug in css-select (known from eg. #728).

Update css-select to 1.2.0

---

Readme.md
lib/api/attributes.js
test/api/attributes.js

Updated version of PR #516 rebased against latest master.  I think I've address feedback to the original PR, added a bit more to the implementation of .prop('style'), plus tests.  For issue #490.

Prop method PR updated

---

lib/api/attributes.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
package.json

Lodash 4 has some braking changes. This PR reflects this and updates lodash dependency to 4.1.0.

Update lodash dependency to 4.1.0

---

Readme.md

Now backers & sponsors will appear automatically on your readme. added badges on top and buttons linking to your public page.

Added backers and sponsors from OpenCollective

---

Readme.md

Readme cleanup

---

index.html

Fixes cheeriojs/cheeriojs.github.io#1

replace occurrences of MatthewMueller/cheerio with cheeriojs/cheerio

---

CNAME

See cheeriojs/cheeriojs.github.io#1
This is the third step of the [process][1].
[1]: https://dns.js.org/

cname: cheerio.js.org

---

Readme.md

Callback passed to function `filter` get called with 2 arguments (`index` and `element`).

Update .filter function docs.

---

Readme.md

Hey folks!
I'm planning to try out a sponsored job board on this repository over the next couple weeks. I'm hoping this can bring in some extra cash to fuel further development and improvement of this library.
If you have any questions, thoughts or concerns, please let me know – thanks!

Experiment with a job board

---

lib/api/attributes.js
test/api/attributes.js
test/api/manipulation.js

Added a few tests to increase coverage by a small amount.
Cleaned up attributes.val() tests to match the existing style.
Removed a small unreachable if statement.

Test suite housekeeping

---

lib/static.js
test/cheerio.js

Added $.merge following jquery's spec
Added test cases for $.merge
Closes [Issue#973](https://github.com/cheeriojs/cheerio/issues/973)

Added $.merge following jquery's spec

---

Readme.md

I found it to be pretty difficult to navigate the Readme (Ctrl+F has a tendency to hit examples first) so I added a table of contents. Each section is collapsed because otherwise the table of contents would be enormous.

Add table of contents

---

Readme.md

Fix Spelling

---

lib/api/attributes.js
test/api/attributes.js

Suggested fix for #993 
Thanks

added support for inherited props in .props(...) validation

---

.eslintrc.json
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/parse.js
lib/static.js
lib/utils.js
package.json
test/api/attributes.js
test/api/css.js
test/api/forms.js
test/api/manipulation.js
test/api/traversing.js
test/api/utils.js
test/cheerio.js

...and format remaining codebase with prettier. Much easier to review the individual commits.

 Add eslint-plugin-jsdoc, improve documentation

---

Readme.md

As Felix required, added a markdown link with English description to the new URL of the Chinese readme article.

Chinese readme link added on main readme

---

lib/api/attributes.js
test/api/attributes.js

feat(attributes): Have `removeAttr` accept a list of attributes to remove

---

lib/api/attributes.js
test/api/attributes.js

feat(prop): Support `prop('innerHTML')`

---

lib/api/attributes.js
test/api/attributes.js

Fixes #883
Fixes #927
Fixes #1364

fix(prop): Update attribute value when setting prop

---

lib/parse.js
test/cheerio.js

fix(load): Support passing a single element

---

lib/api/manipulation.js
test/api/manipulation.js

fix(replaceWith): Fix replacing element with itself

---

lib/api/traversing.js
test/api/traversing.js

fix(find): Make it possible to `find` siblings

---

lib/api/forms.js
lib/api/manipulation.js
test/api/manipulation.js
test/fixtures.js
types/index.d.ts

**.wrapAll** API method
* added tests, what I was able compare with jQuery.
* documentation added based on jQuery
* examples tested with cheerio
* I didn't compare results with implementation in #748

.wrapAll API method

---

.github/workflows/codeql.yml

Runs only on main and PRs against main, and on schedule.
* https://github.com/github/codeql-action

Add CodeCQL Action

---

Readme.md

~~I removed the coveralls badge since the integration doesn't work right now.~~
Restored this since it seems to work fine in #1600

Update Readme.md badges

---

package.json

eslint: remove `--ignore-path`

---

.github/workflows/site.yml
CNAME
jsdoc-config.json

Also remove the `CNAME` file (now configured by the action) and change the output directory to only `docs`.

chore(actions): Use `actions-gh-pages`

---

.eslintrc.json
benchmark/benchmark.js
benchmark/suite.js
index.js
lib/api/attributes.js
lib/api/css.js
lib/api/forms.js
lib/api/manipulation.js
lib/api/traversing.js
lib/cheerio.js
lib/options.js
lib/parse.js
lib/parsers/htmlparser2.js
lib/parsers/parse5.js
lib/static.js
lib/utils.js
test/__fixtures__/fixtures.js
test/api/attributes.js
test/api/css.js
test/api/deprecated.js
test/api/forms.js
test/api/manipulation.js
test/api/traversing.js
test/api/utils.js
test/cheerio.js
test/parse.js
test/xml.js

Only a single change (in `lib/static.js`) was necessery as a consequence.

refactor: Enable strict mode for all files

---

test/api/attributes.js
test/cheerio.js

* eslint ignore jest/expect-expect
* I tried add some diversity with tests

added some tests

---

.github/workflows/benchmark.yml
.github/workflows/ci.yml
.github/workflows/lint.yml
.github/workflows/site.yml

* remove unneeded CI env variable; it's already set by the runner
* lowercase `runner.os`

Update CI config

---

test/cheerio.js

issue #1092 seems to be resolved, but added test for it.

added test for issue gh-1092

---

.github/workflows/sponsors.yml
Readme.md
package-lock.json
package.json
scripts/fetch-sponsors.ts
tsconfig.eslint.json

Also exclude sponsors that don't qualify for inclusion on the website and readme.

chore(docs): Automatically update sponsors in README

---

Readme.md
src/api/manipulation.ts
src/cheerio.ts
src/index.ts
src/load.ts
src/parse.spec.ts
src/parse.ts
src/parsers/htmlparser2-adapter.ts
src/parsers/parse5-adapter.ts
src/slim.ts
src/static.ts

feat(parsers): Add `slim` export, move to factory fns

---

src/index.ts

Fixes #1186
@chocolateboy I'd love to get a 👍 from you, in case you're still interested in this!

feat: Make it possible to specify custom selectors

---

src/api/manipulation.ts
src/load.ts

Adresses https://github.com/cheeriojs/cheerio/commit/b64cb31bb0d40d9d912a4e3a24a5ad22a5cdfced#r62533007
cc @XhmikosR

refactor: Remove unnecessary code, be more explicit

---

src/cheerio.spec.ts
src/utils.ts

fix(utils): Recognise comments as HTML

---

src/api/attributes.spec.ts
src/api/attributes.ts
src/api/css.ts

fix(types): Add missing `undefined` return value

---

src/index.spec.ts
src/index.ts

fix: Export missing static methods

---

src/api/css.spec.ts
src/api/css.ts

fix(css): Add malformed fields to previous field

---

History.md

docs: update History.md

---

.github/workflows/sponsors.yml
package-lock.json
package.json
scripts/fetch-sponsors.ts

GitHub unfortunately removed the `style` tag, so let's use imgix to resize the avatars.

chore(sponsors): Resize all avatars to 128x128

---

src/__tests__/deprecated.spec.ts
src/__tests__/xml.spec.ts
src/api/attributes.spec.ts
src/api/css.spec.ts
src/api/manipulation.spec.ts
src/cheerio.spec.ts
src/load.spec.ts
src/slim.ts
src/static.spec.ts
src/static.ts

fix(types): Import types from complete paths

---

src/index.ts

fix(index): Fix static string method documentation

---

Readme.md

Adresses https://github.com/badges/shields/issues/8671

docs(readme): Fix CI badge

---

.eslintrc.json
src/__tests__/deprecated.spec.ts
src/api/attributes.ts
src/api/css.ts
src/api/forms.ts
src/api/manipulation.ts
src/api/traversing.ts
src/batteries.ts
src/index.ts
src/load.ts
src/static.ts

Enables several ESLint rules that were disabled.

docs(tsdoc): Improve TSDoc comments

---

.github/workflows/benchmark.yml
.github/workflows/dependabot-automerge.yml
.github/workflows/sponsors.yml
CONTRIBUTING.md
History.md
Readme.md
package.json
src/__tests__/deprecated.spec.ts
src/batteries.ts

Moving out unrelated changes from #2950.

chore(prettier): Set `proseWrap: always`

---

package-lock.json
package.json

ts-node has not been working lately.

Use tsx instead of ts-node

---

src/api/manipulation.ts
src/api/traversing.ts
src/index.ts
src/slim.ts

To make `isolatedModules` happy

Add explicit type annotations

---

.github/workflows/ci.yml
website/package-lock.json
website/package.json

And replace Node 14 with 20 and 22

chore(site): Fix web builds

---

Readme.md
website/blog/2024-08-07-version-1.md
website/blog/authors.yml
website/docs/advanced/extract.md

chore(docs): Add 1.0 Announcement Post

---

src/api/attributes.ts

fix(attributes): support `.prop` on document nodes

---

src/__tests__/deprecated.spec.ts
src/api/attributes.ts

docs: Replace `.html` with `.prop` for outerHTML

---

src/api/attributes.spec.ts
src/api/extract.spec.ts

test(attributes): Add tests for missing href prop

---

.eslintrc.json
package-lock.json
package.json
src/api/extract.spec.ts
vitest.config.ts

Vitest tests are more accurate here.

chore: Replace eslint-expect-type with vitest type tests

---

package-lock.json
package.json
src/index.spec.ts
src/index.ts

Fixes #4688, #4618
- Bumps the minimum NodeJS version in line with Undici@7
- Fixes `maxRedirections`

Fix Undici issues
